### ISSUE TITLE
Some packages are outdated, use dependabot workflow ?

### ISSUE THREAD

**Issue by maximilien-noal** [paulirwin/JavaToCSharp#73]
AvaloniaUI 11.0.4 just released.

Automatic PRs could be submitted by [dependabot](https://github.com/dependabot).

Exemple: https://github.com/OpenRakis/Cryogenic/blob/main/.github/dependabot.yml

```
# generated by dependadotnet
# https://github.com/dotnet/core/tree/master/samples/dependadotnet
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
```
